# Generated by Django 2.2.6 on 2019-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(choices=[('WESTERNUNION', 'Western Union'), ('BANKTRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
