# Generated by Django 2.2.6 on 2019-11-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20191114_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-record_date']},
        ),
    ]
