# Generated by Django 2.2.6 on 2019-11-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-record_date']},
        ),
    ]
