# Generated by Django 2.2.6 on 2019-11-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191109_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
